services:
  maria-db:
    image: mariadb:latest
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect","--innodb_initialized" ]
      start_period: 30s
      start_interval: 1s
      interval: 30s
      retries: 3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - maria-db-data:/var/lib/mysql
    env_file: .env
  php-my-admin:
    image: phpmyadmin:latest
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - "${PHP_MY_ADMIN_PORT:-8080}:80"
    depends_on:
      maria-db:
        condition: service_healthy
    env_file: .env
  tube-tracker:
    build:
      dockerfile: TubeTracker/Dockerfile
    ports:
      - "${APP_PORT:-80}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
    depends_on:
      maria-db:
        condition: service_healthy
      ollama:
    env_file: .env
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama-data:/root/.ollama

volumes:
  maria-db-data:
  ollama-data: